---
title: "Домашнее задание 2"
output:
  html_document:
    df_print: paged
  pdf_document: default
header-includes:
- \usepackage[russian]{babel}
- \usepackage{hyperref}
- \hypersetup{ colorlinks = true, urlcolor = blue}
---

## Задание 1
* belki <- 3
* strelki <- 3
```{r, echo=FALSE}
Sys.setlocale(,"ru_RU")
belki <- 3
strelki <- 3
if(belki < strelki) {
  print('Победила команда Стрелки')
} else if(belki > strelki) {
  print('Победила команда Белки')
} else {
  print('Ничья')
}
```
## Задание 2

```{r, echo=FALSE}
temp <- c(-8, -5, 0, 2, -6, -9, -8, -12, -11, -7)
min <- -9.8
max <- -3.7
for(i in temp){
  if (i>max) {
    cat(i,'Температура выше нормы','\n')
  } else if (i<min) {
    cat(i,'Температура ниже нормы','\n')
  } else {
    cat(i,'Температура в норме','\n')
  }
}
```

## Задание 3
* 20 / 23
```{r, echo=FALSE}
progress <- function(number.done, number.all){
  print(round(number.done/number.all*100,2))
}
progress(20,23)
```

## Задание 4
* 1,3,-1,0
```{r, echo=FALSE}
assessment <- function(profit){
  profit.new <- profit
  for(i in 1:length(profit)){
    if(profit[i]>0){
      profit.new[i] <- 1
    } else {
      profit.new[i] <- 0
    }
  }
  return(profit.new)
}
print(assessment(c(1,3,-1,0)))
```

## Задание 5
* 1,0,-1,4
```{r, echo=FALSE}
assessment <- function(profit){
  return(ifelse(profit>0, 1, 0))
}
print(assessment(c(1,0,-1,4)))
```

